# Generated by Django 3.2.9 on 2021-11-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='threadID',
            field=models.ForeignKey(db_column='threadID', default=0, on_delete=django.db.models.deletion.CASCADE, to='Forum.threadmodel', verbose_name='Thread'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='userID',
            field=models.ForeignKey(db_column='userID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='topicID',
            field=models.ForeignKey(db_column='topicID', default=0, on_delete=django.db.models.deletion.CASCADE, to='Forum.topicmodel', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='userID',
            field=models.ForeignKey(db_column='userID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
