# Generated by Django 3.2.9 on 2021-11-22 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_rename_name_topicmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 12, 40, 10, 226278)),
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 12, 40, 10, 225279)),
        ),
    ]
