# Generated by Django 3.2.9 on 2021-12-01 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20211122_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 1, 17, 936085)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 1, 17, 935080)),
        ),
    ]
