# Generated by Django 3.2.9 on 2021-12-01 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_auto_20211201_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 55, 58, 30129)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 10, 55, 58, 29130)),
        ),
    ]
