# Generated by Django 3.2.9 on 2021-11-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklytips', '0002_auto_20211130_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabletips',
            name='DateAdded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
