# Generated by Django 3.2.9 on 2021-11-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklytips', '0003_alter_sustainabletips_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabletips',
            name='DateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
