# Generated by Django 3.2.9 on 2021-11-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklytips', '0004_alter_sustainabletips_dateadded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sustainabletips',
            options={'verbose_name_plural': 'Weekly Tips'},
        ),
        migrations.AlterModelTable(
            name='sustainabletips',
            table='weeklyTips',
        ),
    ]
