# Generated by Django 3.2.9 on 2021-11-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklytips', '0005_auto_20211201_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabletips',
            name='DateAdded',
            field=models.DateField(),
        ),
    ]
