# Generated by Django 3.2.9 on 2021-11-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklytips', '0007_alter_sustainabletips_dateadded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustainabletips',
            old_name='DateAdded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='sustainabletips',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sustainabletips',
            old_name='Title',
            new_name='title',
        ),
    ]
