# Generated by Django 2.2.12 on 2021-11-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRewards',
            fields=[
                ('ChallengeRewardsID', models.AutoField(primary_key=True, serialize=False)),
                ('Reward', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Challenge Rewards',
                'db_table': 'challenge_rewards',
            },
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('ChallengeID', models.AutoField(primary_key=True, serialize=False)),
                ('Challenge_Title', models.CharField(max_length=45)),
                ('Challenge_Description', models.CharField(max_length=200)),
                ('Commencement', models.DateTimeField()),
                ('Termination', models.DateTimeField()),
                ('Reward', models.ForeignKey(db_column='Reward', default=0, on_delete=django.db.models.deletion.CASCADE, to='Challenges.ChallengeRewards', verbose_name='Reward')),
            ],
            options={
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='UserHasChallenges',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Completion', models.DateTimeField(blank=True, null=True)),
                ('ChallengeID', models.ForeignKey(db_column='ChallengeID', default=0, on_delete=django.db.models.deletion.CASCADE, to='Challenges.Challenges', verbose_name='Challenge ID')),
            ],
            options={
                'verbose_name_plural': 'Users Challenges',
                'db_table': 'user_has_challenges',
            },
        ),
    ]
