# Generated by Django 3.2.9 on 2021-12-01 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='Reward',
            field=models.ForeignKey(blank=True, db_column='Reward', default=0, on_delete=django.db.models.deletion.CASCADE, to='Challenges.challengerewards', verbose_name='Reward'),
        ),
    ]
