# Generated by Django 3.2.9 on 2021-12-01 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Challenges', '0003_alter_challenges_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhaschallenges',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='UserID'),
        ),
        migrations.AlterUniqueTogether(
            name='userhaschallenges',
            unique_together={('UserID', 'ChallengeID')},
        ),
    ]
