# Generated by Django 3.2.9 on 2021-11-22 01:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxAttendees', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('imageLink', models.FileField(blank=True, upload_to='uploads/2021-11-22/')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('eventID', models.ForeignKey(db_column='eventID', default=0, on_delete=django.db.models.deletion.CASCADE, to='Events.event', verbose_name='Event')),
                ('userID', models.ForeignKey(db_column='userID', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations',
            },
        ),
    ]
