# Generated by Django 3.2.9 on 2021-12-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageLink',
            field=models.FileField(blank=True, upload_to='uploads/2021-12-01/'),
        ),
    ]
