# Generated by Django 3.2.9 on 2021-11-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Tips',
                'db_table': 'tips',
                'get_latest_by': ['id'],
            },
        ),
    ]
