# Generated by Django 3.2.9 on 2021-12-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipmodel',
            options={'get_latest_by': ['id'], 'verbose_name_plural': 'Weekly Tips'},
        ),
    ]
